cl_bootnode_privkey: ENC[AES256_GCM,data:e8oXHAnKYjk//ertlr1j3r0Qkhr1JfazqaqgeudIaV2lhgszPgfKhNheGaXldgPwWQWXIBN9ZRaPFLxPh25LIQ==,iv:Nfd9nSXuVbHAknCPXIIPlF0XdFxJ/lvFXcW0iAA8PBI=,tag:/HN5a8i5asYi2qvEXCH9Hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hcthyar6ujws8nmycmvh46f4luptqdxgf90z2a3ducedwmfvzedq7veutp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT25IWVhFV1FkZTNjL3Jp
            d0xZU0VaU0dpMGZ1Nk02ZmpLaXpGQWZIVkVjClE4Q1FCUS8vMGxqM0h3cWZNaUl4
            dmt2WXBHa0xncDU1dDU0ZG9MNG1SVHcKLS0tIDVxS2FmWVF3M0pWdTdyRjBnbHNS
            MHEzZnovYjFWb0kxdExHb0JqWHRXelUKGiTizepacYGYICblS9aCFWBrjVHPFnIJ
            6MjnYzLN9qEFHfSRCgJECF2hq80e91oRiKgMTAhePeS1cm2FmwPmfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T20:37:12Z"
    mac: ENC[AES256_GCM,data:ntAgmb4hFV53sV0FRgnPIAvteiqZpG9ayUNpfEqRuwC5eY7GEFS8TUBbNjDVm/GIGJiaA5ts6aD7CPNir5eI8pK4p0rm1XsQtAMby6BYHK71HLI4v+4r4nXoGeFgBko4XZ4kBiZk3o9Mn4bEhEYpNJvHTcqD3fVCoM8q6O1BnFk=,iv:VAO33VRCCNSWQcWIbd0diXE1mdhQZxgRII7DpxcRWAk=,tag:QqsnUCKALbMFf9nDjdoPJQ==,type:str]
    pgp:
        - created_at: "2023-08-17T08:39:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA32GcoRiZf6pAQ//T3POvY+nKAWmAadyWbAS3sytfFP6nDCevZ0nuBdTQU5y
            riKyt/8EzehCOrDGezFCy0Hk4yRENbXzvqAYNumcC1yxoARwC9L3yBb594+O7PA8
            C4Im23JsHjDEvK59FWVxuA8HYq5Crk90iq1qBAvBOv92i60vGC9EyuRZz4sVp/lE
            L8PB8qv9guzJSdMyyzjiT9mLcbUSJpIUXAPz+pUBGpYhuF2SgGReAsolGAt41AxX
            l1nlreFgnufINGQXx8+YJgOuUSJmzryp4de6yZc7Bc649BprkVqIir2mF1fEtqIQ
            OlgD5zQh/KOuXMpuf8CK2XihtFscIdjfWkZOUkovvWsr+hGEw3WkcPdrATHeRNha
            adJ2uxcTpUYu5+RLJcHsAN4x8TPUbyi80bY0V18sZzb7YGNaVhiMKEGgrPrVkmLr
            /6INLFyqpy5KNQ5tMn7AaQvMpoQ0jD/cSUuP977/hmxKhVt7V/R/b8gYod2B8dLG
            6hW8iGZReZ3mB0QPNEmhhVa6+wo7aYzFVCu6/b0N4BKbULml1Gw3/9m7cXmSR+rn
            +7R0Pt/pG4JnT8TmYjcbngbRvVdLs2GpQmAmDLW/CjUi8VpR4U8jivsP+k0s5J/s
            hTOycrQjI3HjoN9talFUHASYe7+tnmOqeHEIrlH67tTenpZhAf0Ruysnlybn71bS
            UQFpztytq0aKniQKio3TtDgRHpUNELzcEl3yu1cBjEPGn2qFyJx4DLJGT0axYgT6
            i5blhI4E8xEW05I/yVjsTSYCmlUT9fqRxhVeR1YzRDSR+Q==
            =bq0E
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2023-08-17T08:39:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA87Wber4r4dGAQ//X4VihyMfIo54OrBZQ/pHHn6pROL9+Z3lEZHjbU1cLG5F
            PbEPiJ+gzL7Ssp5jetnVoxq4zHz3S2AkAx44KutSvUhbsAmZk4MR5fv5JuzK9081
            Ywp62bgj7M9+yg17Oqp9lHwanOWUpOZqxc63viqJ2ZYskq/tDGqjSIPmGjPqgNUE
            wCMEMLmXz7B2woCE+gULHT7SPeHh2gVTlGy/WLS0rvS3I1kqNg0a7x3Iw8RXsmMt
            fw48Zw6K5gGa5xBo0Zk346JInhDguWIqiuUG4G0eJzBPw8DVOybuPWumiL6RuJ37
            VHLQghGeCktgXJGYweXil699rK7x5y7pDpbSIUhZvvf1KkH0HnfaRY6gseCk3Nmy
            FubJxR9PnJwbidiLUSZfkAXHS8nd8lF6UQsrkaKWQukkYqgUktqpkYjLCPwbtZvL
            Bz8mE+8K4cRhdlNiuZi6H6T+Lbom85T/WYi67xTb9Ed4n8z27gLjyS2DPn/lJFpB
            7NziduiguX4JTIUKYHUYQUNKowVIW6288YVIeqZxXtKlnrkm8UnGAQf+ZPjcBAs4
            Jbq9GIGIdoVOPh02JgRj/vJLCAGPVJx7RDvPxtmj9c+dGCCBbqLKQRPNnNaZq8TA
            1TOIcCQY9pr7jURbMkhEwJ0EzQYGp/nL1DDzoyxnjdY5nsPzFq28fJv3PEdCryzS
            UQGTIHiyfnav6OweaW4ZJVdl2tvhfQ6vqtB5DbOhnzpeQhGv5Jzpetu4hyLjHB9c
            vqgUQXCEH2W2aQ780HTRLcEXWeqa5PI6Kg0sqOgfzAHVdw==
            =7qhJ
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2023-08-17T08:39:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyAQ//YBEwIg9FC6cw/bz9cY3Q5Xi4o9aTWsIvwAnVMThTCXU3
            p0SdzWeJXRJWPdSuqiQF4QghraQiunXM33OnND2r+9D0rZ/7BYfTjvrnXP2gAqbk
            2jyigNTwwnY0opy9m9lI1FSB4ubNASKeZ8/xGSJYxOnFz5QP87e70xgJDSRGgN7n
            QJG/fiikLAbUPKPCp4ydh9bnEkOezUn9FDMhax+YEW8QrPk2NrsW6R9THTmiQiRX
            uM9VU9PB6pF4okq311+ruhm9OjmJP8K4YpQGyTnGkQ6IZOPMT3Y9MzaJbUwzbIj4
            fAQNW80T13xOi4f+vmQyFc2EfC/xFdElTv7xFiYjH4Ol8XQ9tRbkb1sOvkqL/DJ5
            CUZjqsUyXnUSPQMp+xkFWep5iJ6V5j2D4ZIvPIIwl9AbpmIQiHuQXwV1ERO7cYyo
            Y6cM03/G6HZqIkDS/CUK0XnBxkiN5oNSTQ9D/T+TO6bHSUXb98ijr4d0ful7DpWZ
            EnKTjeFU/VLD1Qc9Kgrkfva9CSHVXK+9C2+rlVAP4qZaKKwsBgzjGXBvChYElygB
            GM7F7CzyRuJxmv5lJSXiGtxjAWdJ4M8fZPxiN0dwNGziVkhQPwMTLQODgv1tmatv
            DZrHtur4esHF20qGbVyRzb7FLUQ9LvAdStgtBnXqEMTOSpDAe/cNjQ4VZTGMUkHS
            UQFbgFiQYjdtFg1PG64X0bSQIscivB42cZFsyCd3vzx0iAq8tmPqwaeQ78ya+rTx
            0OyfuNPL70zS5kT8eFZQJwFKZ0DRpPPdW62C7lVM5gQr+A==
            =6bXx
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2023-08-17T08:39:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAw01qfIBwY0JARAAtH5N1Ws/57flNxEJM+2xRw4Vbgjgnp3hChIwOj9uJXqe
            OdyCPf8/Sf6p14oOP4MSiLQAmL346aSiusV0NrIpkkY/3vbvbwVP0p6COAJ9Ts3z
            5ILRcPaRM+XaIYK95232yaUCt12k/SnQX62tgPyrbFhlsTfa3czAzztbP7wnIw1b
            xd/i9hNiV60YoDFK+DRU/sAH2TD+8YmCOZ4ChYhX+heU19Djj7Rm6KDFikMx0RO3
            HlBUUXesIOzwIzdhzrQhfOIeHtHdraJBCFYaOE96q3LmjI80id/FOtdpyhCu7CYs
            opqDTDc8Hjn6wXKHkvmaIYwalOb8KQNLFVfPt5mIPJ46TwfTZOcryWMf1EmEOu/z
            GYUCOF2F4QlQX1ROqGI9rfEAbQ/nv0N6It9WhFiQX89PlJk+p2+DjghznDFXk57Y
            7MSIXodlO2ifR0le6xEtyWtvf2/8VB/aCzg2PzlYSS9aZzdVSgkJob0Bnaye1Lo3
            8B3lzvsR02mDQSS38VvO0qjhsOTIFFD7BonkVslnT6tsSOn+Z1f1ndtCyK0Dv2i3
            Djc62s9nfjC0za44zR1Rt4GOGPN8jXTMU5fwuWfOmXK2ka7rgB1mjvUH8kvuvd9/
            TkR9gVrDNTTTynKCcuqsPBa2qDVTWb4pwRDCjre+Vr72xihMwaHspWQe0/htnOfS
            UQFRouisNETX8byhgruLxMOmaqjXDPCKdyr7Uga+SsIxjq5W0QQBMhDIT6nGRtib
            dy4RC3BX5Z5TmD51eJrw+2Mka5wA+SJ+BuXoheLh7lSnYw==
            =HYnC
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2023-08-17T08:39:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMAwDFOgk9tOQ+AQgAyk3B7KZFhwErf5ENU5kc1bCBasCKtdQF6ppGFSnv61IR
            mfega8fwXHn1JJUcGpEzqxMQ3/xxcMQ5vh2+wAGNfNAlQDQ18T7ChNWmiHr8AcEa
            pQcNZM1ck/v3CSqjoRg+5tuJE1x1KhRrj2kS3Yknwx/SVpJh+yI/ZC+uRSNZeU9a
            RXcyZEU7RbN9S/ENJQzWz+OS9xyzxqbCbF6KEh/XJJRS3/wHppN5VMofnhcK9wjq
            XQAGh8u96hH0x76LAHoe6yJZ+AJxGrOC+xKItdT6Ulj5XKghN5owK11oBCRxD/cj
            CAypghbV+nqzNJ9CYjnRGOFnvmaq2lQqPuMctP16TdJRAcMF99hazwRxMNidGaVB
            W0da+JKu8nJuK5AAttWRx8k7DCAA8H77BxJckgKO3Y56mc7zo5gbYJxqu0L3rUVe
            d4glihnzd+6WGleSRwVQow/P
            =MoSh
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
        - created_at: "2023-08-17T08:39:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAz4a8AV36xppAQ/7BcNSnmloxlQF2BDNTTM5K0y8H1a7YP+uMUaha8OfY1wn
            /BdzI6997Jr7FHIfGySWrr1zjlFkPmNSwpxUUSGP6f2mw/SBYgk8loASyd1La7HG
            huaNxeXFOboqk//Bv19x1mjQQBnTqcRo5WwtqnU6G/XGt1wqVpwjhbE7GKfATRZj
            YLVqKchU55NfDk/q/6BBLMjQrDdN+UPlgjvP6cP+hXhNv/XpkOXTapcqyIa0JNX0
            VrqHOD0pp9s1uTCoLVDKNeFJ0Vkf1vCMyBDgKZ+2BJglFuCTjLnRKtvcHJbuct8R
            LFWWBL2n+jpGE6F40IB7m93suAamFtGOfm5HTCki1uLKk2VKK+gPSg/S7liWw+LB
            2qDQ+em2O3IbFjuf1H74KEy8eqQmmNI8itZrJJ8ldYjaghWNJj3RJhhTH863DKHq
            mCD5PRaOkQ1HTm4C3rUI2TbLd1SXP7A8oyWjp0OIvZ+c6QzW3Yd8obUpuBL1RWci
            hcSal1yZetEpAgB41ee7yjawnuO4zwZmKfIsVt/uD38UPAQilsSoVDMvPpzH9leQ
            tymyp+aSLEhp4vnAlrk1n7AmDVv6bSBFc2I4LDNlH9NbtM6/lthxjmgyHUOVaZyt
            x7LxrzDj17rqRd8uP8+CdCvq/sxh9KSQlrvx9wmtJsE+6C+YGWO6J2WkxQFKcq7S
            XgHzdi2+P20A0CwZ1KvfyJBKxLsKkq5w5w99P1N0MLPXy9SM4Q+WnqZ0DW3WsLAW
            F2hUL5p8RilfMoVDwEqRWioNnYcRx7vQ+XHEcPzohin9cJHUHiafPMuXdxhbOS0=
            =l5jg
            -----END PGP MESSAGE-----
          fp: 29C50D01122FDE78E257482DAA497EB2610A8435
        - created_at: "2023-08-17T08:39:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DORxA7Ajr8awSAQdACun2q6CAoIzTD9wOLxy8+tmFFk6cqE1lAap3ZfVG3Usw
            LleoLFPablGJKue+t3Hpfv8CkzFe+2hACEgYzWIx59ahkyYgvYq1+Bdwxss+tSKs
            1GgBCQIQrpVbNLh9uXC55G1LMjVOqslhQsJuaLR5RCmPkKNQTdfEKxelgt7cLnbB
            SkkvpeSPx7fonx6miI24oJDo93spRXUj3+ifSLwShR1fBR6gyEgiVPNBlgEmahVb
            eFRoL6KqQpm/kg==
            =zh3R
            -----END PGP MESSAGE-----
          fp: CEA1598FBCBAD929A56F24F21AE82838CB1EA4FB
    unencrypted_suffix: _unencrypted
    version: 3.7.3
