# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/Chart.yaml.j2

apiVersion: v2
name: checkpointz
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: checkpointz
    repository: https://ethpandaops.github.io/ethereum-helm-charts
    version: 0.1.3
