# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/Chart.yaml.j2

apiVersion: v2
name: blobscan
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: blobscan
    repository: https://blobscan.github.io/blobscan-helm-charts/
    version: 0.2.12
  - name: blobscan-api
    repository: https://blobscan.github.io/blobscan-helm-charts/
    version: 0.2.8
  - name: blobscan-indexer
    repository: https://blobscan.github.io/blobscan-helm-charts/
    version: 0.2.9
